name              'vcruntime'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs Microsoft Visual C++ Runtimes'
version           '2.2.9'
source_url        'https://github.com/sous-chefs/vcruntime'
issues_url        'https://github.com/sous-chefs/vcruntime/issues'
chef_version      '>= 12.15'

supports 'windows'
